### ISSUE TITLE
/sys/bus/visorbus/devices/visorbus<n>/client_bus_info should be a debugfs entry

### ISSUE THREAD

**Issue by selltc** [davidker/unisys#100]
[KanBoard-25518](http://ustr-erl-6690.na.uis.unisys.com/?controller=task&action=show&task_id=25518&project_id=37)

In visorbus_main.c, /sys/bus/visorbus/devices/visorbus<n>/client_bus_info should be a debugfs entry instead of a sysfs entry, as per Greg's comment when we recently-submitted a change to `client_bus_info_show()` (see github #90):

```
You do realize that sysfs files are supposed to only be "one value per
file", right? This is going to have to change soon, if you want this
code out of staging.

I'll take these patches now, but please work on a sane API (this really
looks like something for debugfs as no userspace tools should be relying
on it...)
```

**Comment by selltc** [comment]
Fixes on [githubissue-100-upstream-next branch](/davidker/unisys/commits/githubissue-100-upstream-next).

These are checkpatch-clean and tested successfully.

**Comment by selltc** [comment]
Proposed cover letter:

```
Move /sys/bus/visorbus/devices/visorbus<n>/client_bus_info to debugfs

In a 9/28/2016 patch inspection that fixed code within the function that
emits this client_bus_info sysfs entry, GregKH pointed out that this
shouldn't actually be a sysfs entry at all, and in fact belongs in debugfs.
This patchset addresses that.
```

**Comment by selltc** [comment]
I also successfully compiled this code using a .config where `CONFIG_DEBUG_FS` is NOT set, just to be sure I didn't break anything there.

**Comment by davidker** [comment]
8217becc1b416e348d1bc8fcb54c09967e0f4987 fixes this
