### ISSUE TITLE
Get rid of visorchipset_release functions

### ISSUE THREAD

**Issue by ghost** [davidker/unisys#110]
[KanBoard-24494](http://ustr-erl-6690.na.uis.unisys.com/?controller=task&action=show&task_id=24494&project_id=37)

```
 > 	return 0;
 > }
 > 
 > static int
 > visorchipset_release(struct inode *inode, struct file *file)
 > {
 > 	return 0;
 > }
 ```

 If you do nothing in a release function, then don't provide it at all.

**Comment by ghost** [comment]
**Branch:** githubissue-110-for-later-TurningWrenches
**Commit(s):** 
9cc183333f5d562669970961e1baf906ccff4fe4
**checkpatch-cleared:** Yes
**T710-1 verified:** Yes

```
$ grep -rn "visorchipset_release" drivers/staging/unisys/* | wc -l
0
$ grep -rn "visorchipset_dev_release" drivers/staging/unisys/* | wc -l
0
```

**Comment by ghost** [comment]
@davidker 

Do you remember where we left this?

**Comment by davidker** [comment]
Do we still have it?  My belief is we got rid of the things that required us to have a release function so it just disappeared. We can close this.
