### ISSUE TITLE
Implement Release Function(s)

### ISSUE THREAD

**Issue by ghost** [davidker/unisys#115]
```
 > 
 > static struct attribute_group visorchipset_install_group = {
 > 	.name = "install",
 > 	.attrs = visorchipset_install_attrs
 > };
 > 
 > static struct attribute *visorchipset_parahotplug_attrs[] = {
 > 	&dev_attr_devicedisabled.attr,
 > 	&dev_attr_deviceenabled.attr,
 > 	NULL
 > };
 > 
 > static struct attribute_group visorchipset_parahotplug_group = {
 > 	.name = "parahotplug",
 > 	.attrs = visorchipset_parahotplug_attrs
 > };
 > 
 > static const struct attribute_group *visorchipset_dev_groups[] = {
 > 	&visorchipset_install_group,
 > 	&visorchipset_parahotplug_group,
 > 	NULL
 > };
 > 
 > static void visorchipset_dev_release(struct device *dev)
 > {
 > }
 ```
 As per the documentation in the Linux kernel source tree, I get to
 make fun of you here in public.  You are herby mocked and when I see
 this I want to jump up and down and scream.
 
 Do you think that the kernel was giving you a message of "no release
 function" for grins and giggles?  No, that code was there to save your
 from yourself.  By providing an empty function, did you think that you
 were ok in that you outsmarted it?

**Comment by davidker** [comment]
Sameera patch fixes this it is currently in staging-next.
