### ISSUE TITLE
No kerneldoc for static functions

### ISSUE THREAD

**Issue by ghost** [davidker/unisys#119]
```
 > }
 > 
 > /**
 >  * initialize_controlvm_payload_info() - init controlvm_payload_info struct
 ```
 kerneldoc for a static function?  Ick, no.
 
```
 > }
 > 
 > /**
 >  * visorchipset_chipset_notready() - sends chipset_notready action
 >  *
 >  * Send ACTION=offline for DEVPATH=/sys/devices/platform/visorchipset.
 >  *
 >  * Return: CONTROLVM_RESP_SUCCESS
 ```
 kerndoc for a static function? No.
 
```
 >  */
 > static int
 > visorchipset_chipset_notready(void)
 > {
 > 	kobject_uevent(&visorchipset_platform_device.dev.kobj, KOBJ_OFFLINE);
 ```
 And the kerndoc is toally wrong compared to the code :(
 
 You were better off not documenting it, it would have at least done what
 you said it would do...

``` 
 > }
 > 
 > /**
 >  * read_controlvm_event() - retreives the next message from the
 >  *                          CONTROLVM_QUEUE_EVENT queue in the controlvm
 >  *                          channel
 >  * @msg: pointer to the retrieved message
 >  *
 >  * Return: true if a valid message was retrieved or false otherwise
 >  */
 ```
 kerndoc :(

**Comment by ghost** [comment]
To look for potential violations, I performed the following ```grep``` search on the Unisys driver directory to see which files I need to scan through...

```
$ grep -rl "static" drivers/staging/unisys/
drivers/staging/unisys/visorbus/visorchannel.c (x)
drivers/staging/unisys/visorbus/visorbus_main.c (x)
drivers/staging/unisys/visorbus/controlvmchannel.h (x)
drivers/staging/unisys/visorbus/visorchipset.c (x)
drivers/staging/unisys/visorbus/vbuschannel.h (x)
drivers/staging/unisys/visorbus/vmcallinterface.h (x)
drivers/staging/unisys/visorbus/visorbus_private.h (x)
drivers/staging/unisys/visorinput/visorinput.c (x)
drivers/staging/unisys/visornic/visornic_main.c (x)
drivers/staging/unisys/visorhba/visorhba_main.c
drivers/staging/unisys/include/iochannel.h (x)
drivers/staging/unisys/include/channel.h (x)
```

**Comment by ghost** [comment]
**Questions**
```
visorhba_main.c/visorhba_queue_command_lck()
```

**Comment by ghost** [comment]
**Branch:** githubissue-119-upstream-next-TurningWrenches
**Commit(s):** 
These patches are not directly related to the GitHub issue, but are important related changes:
4d743f5c356a9c8c89c144b39b25c25c0070888b
dbfa23ea955daa0817e0c481eefc3e06b181cba7
57a3050c8b8af011dc27ad114f3fa4fe913e22b7
These patches address the GitHub issue:
b40dad13a7e63f41e1b6bd3b7e0c9aabf53f8f62
533ebe0ecde3ef601e926a3dd0f32a2c97766eee
a0ad03deee3ab2409d37bb55ab1111e0b8cd072a
00893cca29269657a6cf1f184937845a7159a6f6
865dc1cb4526339f6ce181228104359ec989cde9
70d6243220183de8799f2a999574946621d2d33a
The patches were assembled in top-to-bottom order.
**checkpatch-cleared:** Yes
**T710-1 verified (smoke-test):** Yes

**Comment by davidker** [comment]
Greg accepted this.
