### ISSUE TITLE
Describe PUTFILE signature is it used?

### ISSUE THREAD

**Issue by davidker** [davidker/unisys#123]
Get rid of the putfile structures since we don't use that controlvm command in guests.

**Comment by davidker** [comment]
I by accident dumped the patch into upstream-next.

**Comment by davidker** [comment]
Patch for review is: 
b5548d305b4e779a19d296b9b4aa49147492d68e

**Comment by michael-didomenico** [comment]
"that is no longer being used" --> "that are no longer being used"

`Reviewed-by: Tim Sell <Timothy.Sell@unisys.com>`

**Comment by selltc** [comment]
GRRRR... Not sure how I got logged in as Mike again!!

**Comment by davidker** [comment]
Thanks, I think you are just trying to improve our outside contribution amount!

**Comment by davidker** [comment]
Committed to staging-next at 85afaa6
