### ISSUE TITLE
Clean up #defines (right hand)

### ISSUE THREAD

**Issue by ghost** [davidker/unisys#125]
```
Right hand alignment needs to be cleaned up and consistent. 

 > #define POLLJIFFIES_CONTROLVMCHANNEL_FAST   1
 > #define POLLJIFFIES_CONTROLVMCHANNEL_SLOW 100
 
 Right-hand alignment?  That's a glutton for punishment.
```

**Comment by ghost** [comment]
```
$ grep -rl "#define" drivers/staging/unisys/
drivers/staging/unisys/visorbus/visorchannel.c (x)
drivers/staging/unisys/visorbus/visorbus_main.c (x)
drivers/staging/unisys/visorbus/controlvmchannel.h (x)
drivers/staging/unisys/visorbus/visorchipset.c (x)
drivers/staging/unisys/visorbus/vbuschannel.h (x)
drivers/staging/unisys/visorbus/vmcallinterface.h (x)
drivers/staging/unisys/visorbus/visorbus_private.h (x)
drivers/staging/unisys/visorinput/visorinput.c (x)
drivers/staging/unisys/visorinput/ultrainputreport.h (x)
drivers/staging/unisys/visornic/visornic_main.c (x)
drivers/staging/unisys/visorhba/visorhba_main.c (x)
drivers/staging/unisys/include/iochannel.h (x)
drivers/staging/unisys/include/visorbus.h (x)
drivers/staging/unisys/include/channel.h (x)
```

**Comment by ghost** [comment]
**Branch:** githubissue-125-upstream-next-TurningWrenches
**Commit(s):** 
874134d6858fae29d705f11b8e8211d45e26c695
0b4c2bc4ad76377cf842a0f96eac8dfb87401cf9
69cbb687aef4f69eba21a356adf35e1efa86677b
e394ddcdd311a40dbb930bb8936f6cfd5b0dfc0c
7949ffb7846bf2404b9a7a063fd5208fc96d0143
51936a15c743acabd409e674bc5177dd1f43563e
679ca7ceae2a1735806e5c76ae92a13e5644ab7e
325119b6f5e3dc27e20db09377f68812358e1fa9
30770c03b6a594eeb99cff8c69a05a0fffcd3c6a
f641fcc1fe48a61e86c5c2081daf86209b6acba8
f558984f6b6cb08a12bac28c847f61f09fe9d5da
**checkpatch-cleared:** Received checkpatch warnings that may have already existed, but my changes re-triggered them?

David ran branch through auto-inspection scripts, and got the following output:
```
Patch series  changed checkpatch warnings from 39 to 39
Patch series  changed define warnings from 44 to 44
Patch series  changed smatch warnings from 10 to 10 
```
**T710-1 verified (smoke-test):** Yes

**Comment by ghost** [comment]
Is this now extinct? @davidker

**Comment by davidker** [comment]
Don't know, I think we still need to go through the #defines and see if we still have any that are right aligned.

**Comment by davidker** [comment]
I'm closing this since all changes are in upstream-next or no longer needed.
