### ISSUE TITLE
Fix up verbose function comments in visornic. [staging-testing]

### ISSUE THREAD

**Issue by davidker** [davidker/unisys#17]
From: Greg KH [mailto:gregkh@linuxfoundation.org] 
Sent: Wednesday, March 16, 2016 10:07 PM
To: Gavin O'Leary gavinoleary3@gmail.com
Cc: Kershner, David A David.Kershner@unisys.com; Romer, Benjamin M Benjamin.Romer@unisys.com; *S-Par-Maintainer SParMaintainer@unisys.com; devel@driverdev.osuosl.org; linux-kernel@vger.kernel.org
Subject: Re: [PATCH] drivers: staging: unisys: visornic: Fixed block comment coding style warnings

On Wed, Mar 16, 2016 at 07:01:51PM -0700, Gavin O'Leary wrote:

> Fixed block comment checkpatch warnings.
> ## Signed-off-by: Gavin O'Leary gavinoleary3@gmail.com
> 
>  drivers/staging/unisys/visornic/visornic_main.c | 11 ++++++-----
>  1 file changed, 6 insertions(+), 5 deletions(-)
> 
> diff --git a/drivers/staging/unisys/visornic/visornic_main.c b/drivers/staging/unisys/visornic/visornic_main.c
> index 0519470..eefbacc 100644
> --- a/drivers/staging/unisys/visornic/visornic_main.c
> +++ b/drivers/staging/unisys/visornic/visornic_main.c
> @@ -1315,12 +1315,14 @@ visornic_rx(struct uiscmdrsp _cmdrsp)
>               }
>               if (found_mc)
>                   break;  /_ accept packet, dest
> -                        matches a multicast
> -                        address */
> -                      \* matches a multicast
> -                      \* address
> -                      */

That looks horrible, don't you think?

> ```
>       }
>   } else if (skb->pkt_type == PACKET_HOST) {
>       break;  /* accept packet, h_dest must match vnic
> ```
> -                mac address */
> -              \* mac address
> -              */

Same here.

Please fix up to look better, that's your goal, right?

thanks,

greg k-h

**Comment by selltc** [comment]
Greg committed this to staging-testing 5/6, and later to staging-next 5/9:
- commit 77c9a4ae81940fb97a8ec720b64b94a999698963
