### ISSUE TITLE
visorchannel.nbytes vs visorchannel.size[upstream]

### ISSUE THREAD

**Issue by AlexanderCurtin** [davidker/unisys#18]
The visorchannel struct both has nbytes and bytes. Both are set to the allocated bytes for the channel. They seem to be used interchangeably. Why?

**Comment by selltc** [comment]
I think one of the fields is indeed extraneous, and we should fix the code to use one or the other.

**Comment by AlexanderCurtin** [comment]
Looking back on it, the two attributes are `visorchannel.nbytes' and 'visorchannel.size'.

**Comment by ghost** [comment]
The issue is repaired:
- **branch**: visorchannel_nbytes_v_size_issue, commit 134a8f0
- **checkpatch-cleared**: yes
- **T710-1 verified**: yes

**Comment by davidker** [comment]
David, 

I switched the title of the patch to staging: Unisys: visorchannel: remove redundant member size

The previous headline was dealing too much with "issue" which I don't think makes sense in the kernel logs. Let me know if you have problems with the changed. It is currently in upstream-next and being processed.

**Comment by ghost** [comment]
The new title looks great!
