### ISSUE TITLE
visorbus_device.description never used [upstream]

### ISSUE THREAD

**Issue by AlexanderCurtin** [davidker/unisys#21]
Defined in visorbus.h and never used.

**Comment by AlexanderCurtin** [comment]
This is also true for switch_no and internal_port_no.

**Comment by AlexanderCurtin** [comment]
@davidker `switch_no` and `internal_port_no` were both removed in the branch [issue/21-upstream-next-curtinap-visor_device]

**Comment by davidker** [comment]
in staging-next
