### ISSUE TITLE
remove/fix up TODOs

### ISSUE THREAD

**Issue by davidker** [davidker/unisys#28]
Pulled this from the for-later branch (since interrupt todo's have been done). Determine if we need to do them and then write stories, if we don't need them get rid of the TODOs.

kershnda@USTR-ERL-4458[]:~/kernel/master/unisys/drivers/staging/unisys$ find . -print | xargs grep -r -n TODO
./visorbus/visorchipset.c:435:  PARSERSTRING_NAME, /\* TODO: only PARSERSTRING_NAME is used ? _/
./TODO:1:TODO:
./visorhba/visorhba_main.c:604: \*       TODO: Make this per vhba
./include/guestlinuxdebug.h:138:/_ TODO-> Info currently doesn't show, so we set info=warning _/
./visorbus/visorchipset.c:435:  PARSERSTRING_NAME, /_ TODO: only PARSERSTRING_NAME is used ? _/
./visorbus/visorchipset.c:435:  PARSERSTRING_NAME, /_ TODO: only PARSERSTRING_NAME is used ? _/
./TODO:1:TODO:
./visorhba/visorhba_main.c:604: \*       TODO: Make this per vhba
./visorhba/visorhba_main.c:604: \*       TODO: Make this per vhba
./include/guestlinuxdebug.h:138:/_ TODO-> Info currently doesn't show, so we set info=warning _/
./include/guestlinuxdebug.h:138:/_ TODO-> Info currently doesn't show, so we set info=warning */
kershnda@USTR-ERL-4458[]:~/kernel/master/unisys/drivers/staging/unisys$

**Comment by davidker** [comment]
This is closed in for-later. @selltc should we leave this open until we are in staging-next?

**Comment by selltc** [comment]
I would think close it.
