### ISSUE TITLE
Eliminate vaguely named variables [upstream]

### ISSUE THREAD

**Issue by davidker** [davidker/unisys#3]
char s[99]
x
t

Take care of these.

**Comment by AlexanderCurtin** [comment]
Is patch dd22ded11dc8a11026fe9f8dbcc711cd49794aae about the right general idea?

**Comment by AlexanderCurtin** [comment]
e01bf1c4533ccfc0ca2db9df514bf239ef3f60ca should removes the "s[99]" bit.

**Comment by AlexanderCurtin** [comment]
I ended up replacing 'p' with 'pos' and 'x' with 'shift' in client_bus_info_show. not sure if the first one was overkill.

**Comment by AlexanderCurtin** [comment]
At this point, visorbus_main.c should be clean.

**Comment by davidker** [comment]
Moved the patches over to upstream-next. Reworking a couple of the comments since they reference github issues.

**Comment by davidker** [comment]
Are you planning on getting rid of the "rc" as well?

**Comment by selltc** [comment]
FWIW, I finally got around to reading https://github.com/davidker/unisys/blob/staging-next/Documentation/CodingStyle, and it basically says this about temporary variable names:

```
LOCAL variable names should be short, and to the point.  If you have
some random integer loop counter, it should probably be called "i".
Calling it "loop_counter" is non-productive, if there is no chance of it
being mis-understood.  Similarly, "tmp" can be just about any type of
variable that is used to hold a temporary value.
```

So given that `i` is ok for a temporary int, I'm not sure why `s` isn't ok for a temporary string.  Perhaps we should just quote the CodingStyle text the next time we're called out for something like this.

**Comment by davidker** [comment]
greg has accepted into staging-testing last night, so I'm closing this.
