### ISSUE TITLE
Sonarqube visorchipset unused functions and struct members

### ISSUE THREAD

**Issue by arfvidsonUIS** [davidker/unisys#30]
struct or union member 'putfile_active_buffer::pnext' is never used.
struct or union member 'putfile_request::file_request_number' is never used.
struct or union member 'putfile_request::data_sequence_number' is never used. 
The function '__check_major' is never used.
The function '__check_visorbusregwait' is never used.
The function '__check_visorbusregwait' is never used.

**Comment by arfvidsonUIS** [comment]
they are used in module_param_named(major, visorchipset_major, int, S_IRUGO)
and
module_param_named(visorbusregwait, visorchipset_visorbusregwait, int, S_IRUGO)

So they maybe needed. So I'm only going to remove  the unused struct members until someone reviews it.

**Comment by davidker** [comment]
Made comments based on the patch. I think we need to get rid of one more comment.

**Comment by selltc** [comment]
Shouldn't we be linking to a patch from here?  Could someone supply a link to the commit?

**Comment by selltc** [comment]
Greg committed this to staging-testing 5/6, and later to staging-next on 5/9:
- commit 456743c357895678431c91c7305d8abaabc92781 - staging: unisys: remove unused struct members
