### ISSUE TITLE
SonarQube visorbus_main.c %d in format string (no. 2) requires 'int' but the argument type is 'unsigned int'.

### ISSUE THREAD

**Issue by arfvidsonUIS** [davidker/unisys#32]
%d in format string (no. 2) requires 'int' but the argument type is 'unsigned int'.
Line with issue
436

**Comment by ghost** [comment]
**branch:** visorbus_format_string, commit: caa99b7
**checkpatch-cleared:** yes
**T710-1 verified:** yes

**Comment by selltc** [comment]
8/15: Greg applied this to staging-next with:
- commit 7f71e48cad66f178e3ad5ad135d9c68d9a2a4c6a - staging: unisys: visorbus: modify format string to match argument
