### ISSUE TITLE
visorhba: visorhba_init(): return a literal 0 on success[upstream]

### ISSUE THREAD

**Issue by selltc** [davidker/unisys#40]
Source: Dan Carpenter dan.carpenter@oracle.com Mon 5/2/2016 5:53 AM

> visorhba_init()
> return a literal zero on success.

See [KanBoard-998](http://ustr-erl-6690.na.uis.unisys.com/?controller=task&action=show&task_id=998&project_id=37)

**Comment by ghost** [comment]
**branch:** visorhba_init_return_0, commit 3c36059
**checkpatch-cleared:** yes
**T710-1 verified:** yes

**Comment by selltc** [comment]
6/8 - Greg committed this to staging-testing and staging-next:
- commit ab2c3d75451819b4d28ec6dececd299ac03d39ec - staging: unisys: visorhba: return 0 literal
