### ISSUE TITLE
visornic: visornic_rx(): clean up issues involving return value

### ISSUE THREAD

**Issue by selltc** [davidker/unisys#44]
```
1154  /**
1155   *      visornic_rx - Handle receive packets coming back from IO Part
1156   *      @cmdrsp: Receive packet returned from IO Part
1157   *
1158   *      Got a receive packet back from the IO Part, handle it and send
1159   *      it up the stack.
1160   *      Returns void
```

Source: Dan Carpenter dan.carpenter@oracle.com Mon 5/2/2016 5:53 AM

> Actually it returns either zero or one but in a convoluted way.  Update
> it to use literals and update the comment.

See [KanBoard-1002](http://ustr-erl-6690.na.uis.unisys.com/?controller=task&action=show&task_id=1002&project_id=37)

**Comment by davidker** [comment]
Patch?

**Comment by ghost** [comment]
**branch:** visornic_rx_rtn_val, commit 6422c33
**checkpatch-cleared:** yes
**T710-1 verified:**

**Comment by selltc** [comment]
6/8 - Greg committed this to staging-testing and staging-next:
- commit 73e81350ad7a45117c17fb3ec433a266b3fa7d78 - staging: unisys: visornic: change return statements
