### ISSUE TITLE
visornic: visornic_init(): switch error-handling and success-handling[upstream]

### ISSUE THREAD

**Issue by selltc** [davidker/unisys#47]
```
2126          err = visorbus_register_visor_driver(&visornic_driver);
2127          if (!err)
2128                  return 0;
```

Source: Dan Carpenter dan.carpenter@oracle.com Mon 5/2/2016 5:53 AM

> Flip this around.
> 
> ```
> if (err)
>     goto cleanup_debugfs;
> 
>   return 0;
> ```

See [KanBoard-1005](http://ustr-erl-6690.na.uis.unisys.com/?controller=task&action=show&task_id=1005&project_id=37)

**Comment by ghost** [comment]
**branch:** visornic_switch_handling, commit 51f6a1e
**checkpatch-cleared:** yes
**T710-1 verified:** yes

**Comment by selltc** [comment]
```
Reviewed-by: Tim Sell <Timothy.Sell@unisys.com>
```

**Comment by selltc** [comment]
6/8 - Greg committed this to staging-testing and staging-next:
- commit 186896fdf0fd7d4617435986ed79f817eecd3c0f - staging: unisys: visornic: check for error instead of success
