### ISSUE TITLE
write kernel doc for struct putfile_active_buffer {

### ISSUE THREAD

**Issue by arfvidsonUIS** [davidker/unisys#50]
Use this format to write the comments for struct putfile_active_buffer

Example kernel-doc data structure comment.

/**
- struct blah - the basic blah structure
- @mem1:   describe the first member of struct blah
- @mem2:   describe the second member of struct blah,
-      perhaps with more lines and words.
  *
- Longer description of this structure.
  */

**Comment by davidker** [comment]
Putfile is gone.this should be gone as well.
