### ISSUE TITLE
'for-later' interrupts do NOT work in SLES12.0 or RHEL7.2

### ISSUE THREAD

**Issue by selltc** [davidker/unisys#54]
[KanBoard-979](http://ustr-erl-6690.na.uis.unisys.com/?controller=task&action=show&task_id=979&project_id=37)

**Comment by selltc** [comment]
Fixed by commit 57781f99da5a8cb7ae3c1898c9dfb42f7f87111b.  I verified I can boot up the for-later branch with SLES12.0 and RHEL7.2 using this patch.  I'll figure out where the for-later branch soon...

**Comment by selltc** [comment]
If I had to take a guess, I would say that it is commit 527c0b19700536f86c758c12f00b9d48bc7ee194 that is at fault, because that is where `channel_interrupt` **SHOULD** have first been assigned a value of visorhba_isr(), but was **NOT**.  I.e., I think this is a mistake where a necessary change was omitted, rather than a change that messed it up.

**Comment by selltc** [comment]
I went ahead and committed this to our for-later svn mirror in [r29725](https://ustr-svn-1.na.uis.unisys.com/trac/spar/changeset/29725).

**Comment by davidker** [comment]
Thanks! I've incorporated it into for-later which should be up later today.

**Comment by selltc** [comment]
Thanks David.  I now see this fixed in your revised for-later commit 42e3e0a8394e481c0991639bbaac12beee2901f2.

**Comment by selltc** [comment]
In today's version of for-later, verified this is in commit 370f552ac18b871470d55295e4065c556ffc559d.

**Comment by davidker** [comment]
@selltc, can we close this? Or do we keep this open to do checks?

**Comment by michael-didomenico** [comment]
I can't figure why we didn't close this a long time ago...

**Comment by selltc** [comment]
(Sorry... I was accidentally logged in to Mike's account before, as I need that to access SDG's github...)
I can't figure why we didn't close this a long time ago...

**Comment by davidker** [comment]
Closing.. okay I was really confused there for a second.
