### ISSUE TITLE
visorchipset.c:669 remaining_steps_show() warn: XXX passing uninitialized > 'remaining_steps[upstream-next]

### ISSUE THREAD

**Issue by davidker** [davidker/unisys#6]
DanC's smatch run says:

drivers/staging/unisys/visorbus/visorchipset.c:669 remaining_steps_show() warn: XXX passing uninitialized 'remaining_steps

Needs a patch.

**Comment by davidker** [comment]
drivers/staging/unisys/visorbus/visorchipset.c:542 toolaction_show() warn: XXX passing uninitialized 'tool_action' \
drivers/staging/unisys/visorbus/visorchipset.c:609 error_show() warn: XXX passing uninitialized 'error' drivers/staging/unisys/visorbus/visorchipset.c:639 textid_show() warn: XXX passing uninitialized 'text_id' \
drivers/staging/unisys/visorbus/visorchipset.c:669 remaining_steps_show() warn: XXX  passing uninitialized 'remaining_steps'

**Comment by ghost** [comment]
The issue is repaired:

**branch**: passing_uninitialized_var_issue, commit 5e36620
**checkpatch-cleared**: yes
**T710-1 verified**: yes

**Comment by selltc** [comment]
Greg committed this to staging-next 4/29:
- commit 3a56d700f60cd3cdc2c1429d107f0818555a5b22 - staging: unisys: visorbus: initialize variables
