### ISSUE TITLE
visorbus: Address string parser TODO

### ISSUE THREAD

**Issue by mriswyth** [davidker/unisys#61]
From [Kanban-809](http://ustr-erl-6690.na.uis.unisys.com/?controller=task&action=show&task_id=809&project_id=37)

`/* TODO: only PARSERSTRING_NAME is used ? */`

**Comment by mriswyth** [comment]
Addressed in branch githubissue#61 with 2 commits.

182666f27a2a180ad7e4ab4c511134788b73d054 deletes the now unused enum values.

9b553c67723258fb1be5b49e6374c14f61e22e44 refactors the code so that an enum is not used for a single value.

**Comment by davidker** [comment]
Closed due to db2003f and 046f93d being in staging-next. Thanks Bryan!
