### ISSUE TITLE
Remove struct safe_uis_queue within visorchannel

### ISSUE THREAD

**Issue by ghost** [davidker/unisys#77]
**Branch:** remove_visorchannel_struct; commits: 6eeab289faa75bb2ea935065d90556dda136be00
**Upstream:** upstream-next
**checkpatch-cleared:** Yes
**T710-1 verified:** Yes

**Comment by TurningWrenches** [comment]
**Branch:** remove_visorchannel_struct; commits: 6eeab289faa75bb2ea935065d90556dda136be00
**Upstream:** upstream-next
**checkpatch-cleared:** Yes
**T710-1 verified:** N/A

**Comment by davidker** [comment]
Committed to staging-next at 0c77396
