### ISSUE TITLE
visorhba: remove unused interrupt_rcvd from for-later

### ISSUE THREAD

**Issue by arfvidsonUIS** [davidker/unisys#79]
A patch in for-later removes the remaining use of interrupt_rcvd, but leaves the variable defined. This patch should be updated to also remove interrupt_rcvd once for-later is stable enough for patch updates again.

**Comment by arfvidsonUIS** [comment]
https://github.com/davidker/unisys/tree/githubissue-79

**Comment by selltc** [comment]
Patch looks fine.  I would just recommend adding "visorhba:" to the headline, and capitalizing the first letter of the description, i.e.:

```
staging: unisys: visorhba: remove unused interrupt_rvcd

This patch ...
```

**Comment by arfvidsonUIS** [comment]
Thanks Tim! I'll make those changes
