### ISSUE TITLE
Task #24489 - Get rid of waiting for registration

### ISSUE THREAD

**Issue by jaftrain** [davidker/unisys#86]
[Kanboard 24489](http://ustr-erl-6690.na.uis.unisys.com/?controller=task&action=show&task_id=24489&project_id=37)
[GitHub Issue 86](https://github.com/davidker/unisys/issues/86)
[GitHub Issue 86 Branch](https://github.com/davidker/unisys/commits/githubissue%2386)

**Comment by selltc** [comment]
Greg committed to staging-next on 9/20/2016:
- commit 41ef5e5a4ad5044841296098b90b4f9da0d264f4 - staging: unisys: visorbus remove unused module parameter

Please close this issue Jon if you think the above patch is sufficient.

**Comment by selltc** [comment]
David said we can close this, with just the above patch.
