### ISSUE TITLE
Task #24490 - Get rid of unused module options

### ISSUE THREAD

**Issue by jaftrain** [davidker/unisys#87]
[Kanboard 24490](http://ustr-erl-6690.na.uis.unisys.com/?controller=task&action=show&task_id=24490&project_id=37)
[GitHub Issue 87](https://github.com/davidker/unisys/issues/87)
[GitHub Issue 87 Branch](https://github.com/davidker/unisys/commits/githubissue%2387)

**Comment by davidker** [comment]
Patch fd1d882 causes a checkpatch warning in visorchipset.c, please fix and resubmit. 

drivers/staging/unisys/visorbus/visorchipset.c:1013: WARNING: braces {} are not necessary for single statement blocks

**Comment by selltc** [comment]
Greg committed to staging-next on 9/20/2016:
- commit c071b6f541b62f4d143cc4316e4b1167dcaea8fe - staging: unisys: visorbus: move controlvm_payload_bytes_buffered
