### ISSUE TITLE
Remove useless initialization

### ISSUE THREAD

**Issue by wadgaonkarsam** [davidker/unisys#97]
[Kanboard 24493](http://ustr-erl-6690.na.uis.unisys.com/?controller=task&action=show&task_id=24493&project_id=37)
[Github branch](https://github.com/davidker/unisys/tree/githubissue-97)

**Comment by davidker** [comment]
Great job with the patch! Looks good, though looking at the issue, I'm not sure if your patch will allow us to close the patch. I think there are several other spots in the driver that greg would complain about if he had another eight hour flight to look through the code. We might want to comb through the code and see if we can find other spots or at least comb through his response some more to see if we can find some.

**Comment by wadgaonkarsam** [comment]
Thanks David! I'll keep looking for similar initializations in the code. I added back the memset in initialize_controlvm_payload_info().

**Comment by davidker** [comment]
Sameer, I picked up your latest patch and started to review it. The patch itself is fine, however, looking at your signed off line your name is all lowercase, are you sure you want that? The signed-off line is like a legal document and your name should be represented as a signature. Do you want me to fix it, or do you want respin?

**Comment by davidker** [comment]
Actually, I take it back about the patch itself is fine. You probably should have two patches one to do the removal and one to do the move down in the file.

**Comment by davidker** [comment]
The more I think about it, we can probably keep the patch as is, so ignore my previous comment.

**Comment by wadgaonkarsam** [comment]
Thank you David, for the inspection and updating the signed off line.

**Comment by davidker** [comment]
Committed at  c4fe36cd262d5fe710ff9ee43cb99337e8b050de
