### ISSUE TITLE
Remove the "local" variable

### ISSUE THREAD

**Issue by arfvidsonUIS** [davidker/unisys#98]

**Comment by arfvidsonUIS** [comment]
Tasks:
in visorchannel rename it to dest and same with visorbus_private

get rid of local and local_addr in visorchipset 
might be able to get rid of test_message
though if someone does send us a test_message we probably want to ignore it now

**Comment by arfvidsonUIS** [comment]
updated branch githubissue-98 and ready for review

**Comment by arfvidsonUIS** [comment]
checked by running grep -r -n local drivers/staging/unisys/

**Comment by davidker** [comment]
The patch 057c711f8845d14bfdbfb2bd68e1fe737387e6b7fails to compile cleanly when -werror is used on the driver. 

I've accepted the other two patches, but am pulling this one from upstream-next. 

>   LD      init/built-in.o
>   CC      kernel/sys.o
>   CC      kernel/module.o
>   CC      drivers/base/firmware_class.o
>   CC      drivers/staging/unisys/visorbus/visorchipset.o
> ../drivers/staging/unisys/visorbus/visorchipset.c: In function 'parser_init_byte_stream':
> ../drivers/staging/unisys/visorbus/visorchipset.c:1850:2: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-afte
> r-statement]
>   void _mapping = memremap(addr, bytes, MEMREMAP_WB);
>   ^
>   LD      kernel/built-in.o
>   LD      drivers/base/built-in.o
> cc1: all warnings being treated as errors
> make[5]: *_\* [drivers/staging/unisys/visorbus/visorchipset.o] Error 1
> make[4]: **\* [drivers/staging/unisys/visorbus] Error 2
> make[3]: **\* [drivers/staging/unisys] Error 2
> make[2]: **\* [drivers/staging] Error 2
> make[2]: **\* Waiting for unfinished jobs....
> make[1]: **\* [drivers] Error 2
> make[1]: Leaving directory `/home/kershnda/kernel/master/unisys/.build'
> make: **\* [sub-make] Error 2
> FAILED make
> Execution failed: ~/bin/make_commit.sh -w
> and made changes to the index and/or the working tree
> You can fix the problem, and then run

**Comment by arfvidsonUIS** [comment]
Cheers,
Erik Arfvidson

**Comment by davidker** [comment]
I need you to make sure there are no warnings when you compile the patch. My script runs with -werror set for our drivers and it gave the instructions at the end of its error. 

You should be getting warnings when you build our drivers with this patch: 

> ../drivers/staging/unisys/visorbus/visorchipset.c: In function 'parser_init_byte_stream':
> ../drivers/staging/unisys/visorbus/visorchipset.c:1850:2: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-afte
> r-statement]
> void mapping = memremap(addr, bytes, MEMREMAP_WB);

That needs to be fixed before I can send it upstream.

**Comment by davidker** [comment]
Please also change: 

> local_addr = (inmsg.hdr.flags.test_message == 1);

to something like: 

> if ((insmsg.hdr.flags.test_message == 1) &&
>      (inmsg.hdr.flags.response_expected)) {
>             controlvm_respond
>                                 (&inmsg.hdr,
>                                  -CONTROLVM_RESP_ERROR_MESSAGE_INVALID);
>              return true;
> }

**Comment by arfvidsonUIS** [comment]
change function from 4 to 3 parameters
remove local_addr

**Comment by arfvidsonUIS** [comment]
Just updated branch githubissue-98. Ready for submission
